# Generated by Django 5.2.8 on 2025-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
