# Generated by Django 5.2.8 on 2025-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing & Apparel', 'Clothing & Apparel'), ('Groceries', 'Groceries'), ('Tax', 'Tax'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
