# Generated by Django 5.2.4 on 2025-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_transaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name="External Transaction (Don't affect Balance)"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing & Apparel', 'Clothing & Apparel'), ('Groceries', 'Groceries'), ('Tax', 'Tax'), ('Investment', 'Investment'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment')], default='EXPENSE', max_length=20),
        ),
    ]
