# Generated by Django 5.2.4 on 2025-12-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_financialgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing & Apparel', 'Clothing & Apparel'), ('Groceries', 'Groceries'), ('Tax', 'Tax'), ('Investment', 'Investment'), ('Savings', 'Savings'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('active_challenge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_challenges_ids', models.TextField(blank=True, default='')),
                ('last_streak_update', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
