# Generated by Django 5.2.4 on 2025-12-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_transaction_category_gamificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='daily_quests',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of daily quests'),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='last_daily_quest_refresh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
