# Generated by Django 5.2.4 on 2025-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_gamificationprofile_daily_quests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='challenge_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
