# Generated by Django 5.2.4 on 2025-12-09 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_gamificationprofile_challenge_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verified_quest_id',
            field=models.CharField(blank=True, help_text='ID of the quest this transaction verified. Prevents deletion abuse.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='QuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('xp_earned', models.IntegerField()),
                ('coins_earned', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quest_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
