# Generated by Django 5.2.4 on 2025-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_transaction_verified_quest_id_questlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='verified_quest_id',
        ),
        migrations.DeleteModel(
            name='GamificationProfile',
        ),
        migrations.DeleteModel(
            name='QuestLog',
        ),
    ]
