# Generated by Django 5.2.4 on 2025-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_transaction_verified_quest_id_questlog'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='gamificationprofile',
        #     name='active_challenge_id',
        # ),
        # migrations.RemoveField(
        #     model_name='gamificationprofile',
        #     name='challenge_accepted_at',
        # ),
        # migrations.RemoveField(
        #     model_name='gamificationprofile',
        #     name='completed_challenges_ids',
        # ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='active_daily_challenge_id',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='active_weekly_challenge_id',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='daily_challenge_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='last_weekly_quest_refresh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='weekly_challenge_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='weekly_quests',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of weekly quests'),
        ),
    ]
