# Generated by Django 5.2.4 on 2025-12-23 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_questlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('SPEND_LESS', 'Spend Less Than'), ('NO_SPEND', 'No Spend'), ('SAVE', 'Save Amount'), ('STREAK_KEEPER', 'Streak Keeper'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reward_points', models.IntegerField(default=10)),
                ('reward_xp', models.IntegerField(default=50)),
                ('difficulty', models.CharField(choices=[('Basic', 'Basic'), ('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic')], default='Common', max_length=20)),
                ('target_variable', models.JSONField(blank=True, default=dict)),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('last_quest_date', models.DateField(blank=True, null=True)),
                ('last_streak_update', models.DateField(blank=True, null=True)),
                ('savings_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
