# Generated by Django 5.2.4 on 2025-12-23 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dailyquest_gamificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='current_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='difficulty',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='quest_type',
            field=models.CharField(choices=[('NO_SPEND_CATEGORY', 'No Spend (Category)'), ('NO_SPEND_VENDOR', 'No Spend (Vendor)'), ('SAVE_AMOUNT', 'Save Amount'), ('STREAK_KEEPER', 'Streak Keeper'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20),
        ),
    ]
