# Generated by Django 5.2.4 on 2025-12-23 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_dailyquest_current_progress_dailyquest_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquest',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
