# Generated by Django 5.2.4 on 2025-12-25 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing & Apparel', 'Clothing & Apparel'), ('Groceries', 'Groceries'), ('Tax', 'Tax'), ('Investment', 'Investment'), ('Savings', 'Savings'), ('Liabilities', 'Liabilities'), ('Other', 'Other')], default='Other', max_length=50)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment')], default='EXPENSE', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_source', models.CharField(choices=[('MANUAL', 'Manual'), ('VOICE', 'Voice'), ('IMAGE', 'Image')], default='MANUAL', max_length=10)),
                ('is_external', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
