# Generated by Django 6.0 on 2025-12-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment'), ('DEBT_PAYMENT', 'Debt Payment')], default='EXPENSE', max_length=20),
        ),
    ]
