# Generated by Django 5.2.4 on 2025-12-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0003_dailyquest_gamificationprofile'),
        ('Features', '0003_financialgoal'),
    ]

    operations = [
    ]
